version: 2

builds:
  - id: mcp-otel-proxy
    main: ./cmd/mcp-otel-proxy
    binary: mcp-otel-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

dockers:
  - image_templates:
      - "ghcr.io/isitobservable/mcp-otel-proxy:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64
  - image_templates:
      - "ghcr.io/isitobservable/mcp-otel-proxy:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/isitobservable/mcp-otel-proxy:{{ .Version }}"
    image_templates:
      - "ghcr.io/isitobservable/mcp-otel-proxy:{{ .Version }}-amd64"
      - "ghcr.io/isitobservable/mcp-otel-proxy:{{ .Version }}-arm64"
  - name_template: "ghcr.io/isitobservable/mcp-otel-proxy:latest"
    image_templates:
      - "ghcr.io/isitobservable/mcp-otel-proxy:{{ .Version }}-amd64"
      - "ghcr.io/isitobservable/mcp-otel-proxy:{{ .Version }}-arm64"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
